import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CustomLocalizationProvider from "./providers/CustomLocalizationProvider";
import CustomReduxProvider from "./providers/CustomReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <CustomReduxProvider>
        <body className={inter.className}>
          <CustomLocalizationProvider>{children}</CustomLocalizationProvider>
        </body>
      </CustomReduxProvider>
    </html>
  );
}
